# Generated by Django 5.1.6 on 2025-02-12 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('sId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quant', models.IntegerField()),
                ('dop', models.DateField(default=datetime.date(2025, 2, 12))),
            ],
        ),
    ]
