# Generated by Django 5.1.6 on 2025-02-14 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quant', models.IntegerField()),
                ('dop', models.DateField(default=datetime.date(2025, 2, 14))),
            ],
        ),
    ]
